### ISSUE TITLE
Define what is the target

### ISSUE THREAD

**Issue by ybouazza-opthread** [ybouazza-opthread/guitar_audio_transcription#1]

**Comment by ybouazza-opthread** [comment]
Qu'est-ce qu'on sélectionne comme données de target ?

**Comment by Ethanol48** [comment]
thanks to the help of the anonymous person in the article of medium, we could extract the notes in midi format of the notes being played in a determine period of time chosen, also I could develop some functions to extract other metadata of interest, like the total duration of the song
